version: 2.1

jobs:
  unit-tests:
    docker:
      - image: gsornsen/python-ci-cd-container:latest
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            make develop
            make test
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml


workflows:
  main:
    jobs:
      - unit-tests
