name: Build & Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'
      - name: Create virtual environment
        run: make init
      - name: Build module
        run: make build
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: wktplot_dist
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3.0.1
        with:
          name: wktplot_dist
          path: dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          print_hash: true
